baseurl = "https://jt-pandey.tk/"
languageCode = "en-us"
paginate = 5
theme = "hugo-theme-hello-friend"
[languages.en]
copyright = "jatin pandey"
dateFormatList = "2006-01-02"
dateFormatSingle = "2006-01-02"
keywords = "jt-pandey jatin pandey jatinpandey jtpandey Hugo Internet Torrent download"
menuMore = "Show more"
minuteReadingTime = "min read"
newerPosts = "Newer posts"
olderPosts = "Older posts"
readMore = "Read more"
readOtherPosts = "Read other posts"
subtitle = "Sleeping Android"
title = "jt-pandey"
writtenBy = "Written by"
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive"
[languages.en.params.logo]
logoHomeLink = "/"
logoText = "root@jt-pandey:~$"
[params]
contentTypeName = "post"
defaultTheme = "dark"
showMenuItems = 2
showReadingTime = true
toc=false
